# SonarQube project configuration

sonar.projectKey=nwg-notifications
sonar.projectName=nwg-notifications
sonar.projectVersion=0.3.0

sonar.sources=src
sonar.tests=src,tests
sonar.inclusions=**/*.rs
sonar.exclusions=**/target/**
sonar.test.inclusions=**/tests/**

sonar.sourceEncoding=UTF-8
